# JavaScript Node.js CircleCI 2.0 configuration file
# https://circleci.com/docs/2.0/language-javascript/

version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      # check out source code to working directory
      - checkout

      # restore, install and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

  lint:
    docker:
      - image: circleci/node:10

    steps:
      # check out source code to working directory
      - checkout

      # restore cached dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}

      # run code linters
      - run:
          name: Run code linters
          command: npm run lint

  test:
    docker:
      - image: circleci/node:10
        environment:
          NODE_ENV: test
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test

    steps:
      # check out source code to working directory
      - checkout

      # restore cached dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}

      # provide environment variables
      - run:
          name: Provide environment variables
          command: cp .env.example .env

      # ensure database is available
      - run:
          name: Wait for database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # create database
      - run:
          name: Create test database
          command: npx sequelize db:create

      # run database migrations
      - run:
          name: Run database migrations
          command: npx sequelize db:migrate

      # run tests and generate code coverage report
      - run:
          name: Run tests and generate code coverage report
          command: npm run test:coverage

      # save code coverage report as artifact
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  build_lint_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
