openapi: 3.0.2

info:
  title: Listem API
#  description: API description
  version: 0.0.0

servers:
  - url: /api
#    description: Server description

#tags:
#  - name: abc
#    description: Everything about your Pets
#    externalDocs:
#      url: http://docs.my-api.com/pet-operations.htm
#  - name: xyz
#    description: Access to Petstore orders
#    externalDocs:
#      url: http://docs.my-api.com/store-orders.htm

paths:
  /auth:
    post:
#      tags:
#        - xyz
#        - abc
      summary: Authenticate user
#      description: Endpoint desc relevant to all operations in this path
      requestBody:
        description: User credentials
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
#            example:
#              email: email@address.com
#              password: paSSw0rd
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        description: Access token (JWT)
#        externalDocs:
#          description: Learn more about user operations provided by this API.
#          url: http://api.example.com/docs/user-operations/
        '401':
          description: Unauthorized
  /users:
    post:
      summary: Create a user account
#      description: Endpoint desc relevant to all operations in this path
#      responses:
#        '201':
#          description: Created
