openapi: 3.0.3

info:
  title: Listem API
  #description: API description
  version: 0.0.0

servers:
  - url: /api
#    description: Server description

security:
  - BearerAuth: []
  - ApiKeyAuth: []

tags:
  $ref: './tags/index.yml'

paths:
  $ref: './paths/index.yml'

components:
  $ref: './components/index.yml'
